modLoader="lowcodefml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="tacz_airdrop"
version="0.1.0"
displayName="TACZ Airdrop Supplies"
logoFile="assets/tacz_airdrop/logo.png"
description='''Adds localized TACZ military supply drops to Airdrop: Supply Drops using resources only.'''

[[dependencies.tacz_airdrop]]
modId="forge"
mandatory=true
versionRange="[47.3,)"
ordering="NONE"
side="BOTH"

[[dependencies.tacz_airdrop]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"

[[dependencies.tacz_airdrop]]
modId="airdrop_supply_drops"
mandatory=true
versionRange="[1.0.14,)"
ordering="AFTER"
side="BOTH"

[[dependencies.tacz_airdrop]]
modId="tacz"
mandatory=true
versionRange="[0,)"
ordering="AFTER"
side="BOTH"
